name: Build MDriven Turnkey Variants

on:
  push:
    branches:
      - "main"
    paths:
      - "docker/builds/mdriven-turnkey/**"

env:
  IMAGE_NAME: ${{vars.DOCKERHUB_USERNAME}}/mdriven-turnkey

jobs:
  # --- UBUNTU ---
  build-ubuntu-amd64:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Ubuntu AMD64
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/builds/mdriven-turnkey/ubuntu"
          file: Amd64.Dockerfile
          platforms: linux/amd64
          no-cache: true
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:ubuntu-amd64
            ${{env.IMAGE_NAME}}:amd64
  
  build-ubuntu-arm64:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Ubuntu ARM64
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/builds/mdriven-turnkey/ubuntu"
          file: Arm64.Dockerfile
          platforms: linux/arm64
          no-cache: true
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:ubuntu-arm64
            ${{env.IMAGE_NAME}}:arm64
  
  # --- DEBIAN ---
  build-debian-amd64:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Debian AMD64
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/builds/mdriven-turnkey/debian"
          file: Amd64.Dockerfile
          platforms: linux/amd64
          no-cache: true
          push: true
          tags: ${{env.IMAGE_NAME}}:debian-amd64
  
  build-debian-arm64:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Debian ARM64
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/builds/mdriven-turnkey/debian"
          file: Arm64.Dockerfile
          platforms: linux/arm64
          no-cache: true
          push: true
          tags: ${{env.IMAGE_NAME}}:debian-arm64
  
  # --- ALPINE ---
  build-alpine-amd64:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Alpine AMD64
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/builds/mdriven-turnkey/alpine"
          file: Amd64.Dockerfile
          platforms: linux/amd64
          no-cache: true
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:alpine-amd64
            ${{env.IMAGE_NAME}}:musl

  create-manifest:
    needs: [build-ubuntu-amd64, build-ubuntu-arm64]
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Create and Push 'latest' Manifest
        run: |
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:latest \
            ${{ env.IMAGE_NAME }}:ubuntu-amd64 \
            ${{ env.IMAGE_NAME }}:ubuntu-arm64 
      


